---
kind: pipeline
name: redis-operator
steps:

- name: test
  image: l.gcr.io/google/bazel:0.28.1
  commands:
  - ./hack/build/test.sh
  volumes:
  - name: cache
    path: /root/.cache

- name: build and push docker image
  image: l.gcr.io/google/bazel:0.28.1
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/build/push-image.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    ref:
    - refs/heads/master
    - refs/tags/v*

volumes:
- name: cache
  temp: {}

---
kind: signature
hmac: a187e70cb43642463df713cfaae94b11d080d65721d4c1a19768dacc8d8c900f

...
